### ISSUE TITLE
Question about Closed-Set Classifier 

### ISSUE THREAD

**Issue by AlejandroSarrio** [aimerykong/OpenGAN#6]
Hi Dr. Kong!
I have a question about baseline results in Set-up I. During training period, a Resnet-18 model is trained, which is different with compared algorithms, such as [13], [67], [46]. 

These three algorithms both use the same model in 'Lawrence Neal, Matthew Olson, Xiaoli Fern, Weng-Keen Wong, and Fuxin Li. Open set learning with counterfactual images. In ECCV, 2018. 2,'. 

According to a recent paper ' Vaze, S., Han, K., Vedaldi, A., & Zisserman, A. (2021). Open-Set Recognition: A Good Closed-Set Classifier is All You Need. 1–23. http://arxiv.org/abs/2110.06207', `the ability of a classifier to make the 'none-of-above' decision is highly correlated with its accuracy on the closed-set classes.`.

**Comment by aimerykong** [comment]
You are right! We also observed that a better closed-set classifier often led to better open-set recognition accuracy. One can use ResNet50 to obtain better OSR performance. In our paper, we use the simplistic Res18 which is a common architecture without any customized re-design.

**Comment by AlejandroSarrio** [comment]
Thanks for your answer.
