### ISSUE TITLE
Implementation of OpenGAN-0

### ISSUE THREAD

**Issue by e96031413** [aimerykong/OpenGAN#9]
Hello, do you plan to upload the code of OpenGAN-0? 

or can I say [demo_CrossDatasetOpenSet_training.ipynb](https://github.com/aimerykong/OpenGAN/blob/main/demo_CrossDatasetOpenSet_training.ipynb) is the implementation of OpenGAN-0 since it does not use open-set images?

By the way, the implementation of OpenGAN-0 just use ```λo = 0``` in the equation 2, right?

**Comment by aimerykong** [comment]
Hi, you are right on both questions. So the answers are yes, and yes.

**Comment by e96031413** [comment]
Thanks for your reply.
